### ISSUE TITLE
Using ImportNamespaceSpecifier circumvents this rule

### ISSUE THREAD

**Issue by smartinio** [A-Shleifman/eslint-plugin-export-scope#4]
Hi, thanks for this plugin. Not sure if it's intended but this does not error:
```ts
import * as hax from 'some-scoped-module'
```

While this does:
```ts
import { myPrivateThing } from 'some-scoped-module'
```

**Comment by A-Shleifman** [comment]
Thanks for bringing this up. It's not intentional but I'm not sure what's the best way to handle it yet. Similar to dynamic imports, the `* as hax` import statement doesn't give any info about which exports you're planning to access. Maybe the plugin should analyze the rest of the code checking each instance of `hax.{importName}` and displaying the error there.

**Comment by smartinio** [comment]
Yeah that could be a good solution

**Comment by A-Shleifman** [comment]
I'm short on time now. I'll try to find some time for this in 3 weeks.

**Comment by smartinio** [comment]
An alternative would be to treat `import * as hax from 'bar'` the same as `import 'bar'` or `import hax from 'bar'` since it's effectively importing everything.

My guess is that would also only need something like this to work?
```ts
ImportNamespaceSpecifier: (node) => validateNode(node)
```

**Comment by A-Shleifman** [comment]
`import hax from 'bar'` only depends on the default export
`import 'bar'` runs the whole script, so it should depend on file/folder scope.
`import * as hax from 'bar'` can only display an error if there are no importable exports at all. Otherwise, this syntax is valid, so validation should happen later in the code.

`checkIsImportable` function would need to be updated to create a map of all exports/scopes whenever star syntax is used and to check all `hax.{importName}` calls.

**Comment by A-Shleifman** [comment]
@smartinio, try v2.1.0! Please let me know if there are still any issues.
