### ISSUE TITLE
.scope.ts should apply to subdirectories

### ISSUE THREAD

**Issue by ysulyma** [A-Shleifman/eslint-plugin-export-scope#8]
Given the following structure
```
└── src/
  └── common/
    └── utils/
       ├── dom.ts
    ├── config.ts
    ├── .scope.ts
             │
             │
  ╭────────────────────╮
  │ export default '*' │
  ╰────────────────────╯
```
I would expect the items in `dom.ts` to be importable from anywhere. However it seems that the `scope.ts` only gets applied to `config.ts`

**Comment by A-Shleifman** [comment]
This is intentional. Even 'public' folders like `common` can have private exports that shouldn't be accessible by the rest of the codebase. All public exports should have their scope explicitly defined with `@scope`, `@scopeDefault` or `.scope.ts` and it only applies to that export/file/dir. 

The only exception - the root `.scope.ts` of the project. You can make all exports public by default and restrict the scope when required if that's your preferred approach.

**Comment by A-Shleifman** [comment]
Thank you for pointing this out. I will update the README to make it more clear.
